[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Porositos"
name = "PEAK_CTPS"
description = "Substitui o passaporte por uma Carteira de Trabalho!!!! | Replaces the Passport with a Brazilian CTPS Work Permit"
version = "1.0.1"
websiteUrl = "https://github.com/vector-b/PEAK-CTPS"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/ctps/release/com.github.vector-b.PEAK-CTPS.dll"
target = "plugins/"

[[build.copy]]
source = "assets/PassportUV_ctps.png"
target = "plugins/assets/"

[[build.copy]]
source = "assets/Passport_Icon.png"
target = "plugins/assets/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods", ]
